This removes grammatical mistakes from the code.
marticliment/WingetUI pull request #2340
Opened 2024-06-25 16:07 UTC by skanda890

- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**
- [X] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [X] **Have you tested that the committed code can be executed without errors?**
- [X] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features, or does not introduce any useful changes. Thank you for your understanding.

-----

This removes grammatical mistakes from the code.

2024-06-25 16:34 UTC, skanda890 reviewed
This must be fine.

2024-06-25 20:17 UTC, marticliment commented on .github/ISSUE_TEMPLATE/bug-issue.yml_new
> +        - label: I have tested that this issue has not been fixed in the latest [(beta or stable) release].(https://github.com/marticliment/WingetUI/releases/)
Dots cannot be added between the [] and () elements of a hyperlink

2024-06-25 20:18 UTC, marticliment commented on .github/ISSUE_TEMPLATE/bug-issue.yml_new
> +      placeholder: Paste here your WingetUI logs. Click the button on the top-right corner of WingetUI -> WingetUI Log.
Please do not revert UniGetUI to WingetUI

2024-06-25 20:20 UTC, marticliment requested changes

2024-06-25 20:20 UTC, marticliment commented on .github/ISSUE_TEMPLATE/enhancement-improvement.yml
> +        - label: This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template].(https://github.com/marticliment/WingetUI/issues/new?assignees=martic
Dots cannot be added between the [] and () elements of a hyperlink

2024-06-25 20:20 UTC, marticliment commented on .github/ISSUE_TEMPLATE/enhancement-improvement.yml_new
> +        - label: This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template].(https://github.com/marticliment/WingetUI/issues/new?assignees=martic
Dots cannot be added between the [] and () elements of a hyperlink

2024-06-25 20:20 UTC, marticliment commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +        - label: This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template].(https://github.com/marticliment/WingetUI/issues/new?as
Dots cannot be added between the [] and () elements of a hyperlink

2024-06-25 20:20 UTC, marticliment commented on .github/ISSUE_TEMPLATE/feature-request.yml_new
> +        - label: This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template].(https://github.com/marticliment/WingetUI/issues/new?as
Dots cannot be added between the [] and () elements of a hyperlink

2024-06-25 20:20 UTC, marticliment commented on .github/ISSUE_TEMPLATE/hard-crash.yml_new
> +        - label: I have tested that this issue has not been fixed in the latest [(beta or stable) release].(https://github.com/marticliment/WingetUI/releases/).
Dots cannot be added between the [] and () elements of a hyperlink

2024-06-25 20:20 UTC, marticliment commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] **I have read the [contributing guidelines].(https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding) and I agree with the [Code of Conduct].(https://github.com/marticliment/W
Dots cannot be added between the [] and () elements of a hyperlink

2024-06-25 20:20 UTC, marticliment commented on .github/PULL_REQUEST_TEMPLATE.md_new
> +- [ ] **I have read the [contributing guidelines].(https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding) and I agree with the [Code of Conduct].(https://github.com/marticliment/W
Dots cannot be added between the [] and () elements of a hyperlink

2024-06-25 20:20 UTC, marticliment commented on .github/ISSUE_TEMPLATE/bug-issue.yml_new
> +        - label: I have tested that this issue has not been fixed in the latest [(beta or stable) release].(https://github.com/marticliment/WingetUI/releases/)
Dots cannot be added between the [] and () elements of a hyperlink

2024-06-25 20:20 UTC, marticliment commented on .github/ISSUE_TEMPLATE/bug-issue.yml_new
> +      placeholder: Paste here your WingetUI logs. Click the button on the top-right corner of WingetUI -> WingetUI Log.
Please do not revert UniGetUI to WingetUI

2024-06-26 05:38 UTC, skanda890 commented
This also solves #2343

2024-06-26 10:12 UTC, marticliment approved these changes

2024-06-26 10:12 UTC, merged